### ISSUE TITLE
What's the point of `linux-firmware-git` as a dependancy?

### ISSUE THREAD

**Issue by Weather-OS** [OzzyHelix/obs-studio-amf-tmpfix-for-arch#1]

**Comment by OzzyHelix** [comment]
when compiling obs with the PKGBUILD the option for AMF didn't appear in OBS until I installed `linux-firmware-git` so I assumed that `linux-firmware-git` would be needed to get AMF working in OBS correctly with the PKGBUILD and provided patches. you need a specific firmware to work with the pro driver that `linux-firmware-git` provides

**Comment by OzzyHelix** [comment]
if you have any other questions feel free to ask them but I'm going to close this issue as complete

**Comment by CcoderN1** [comment]
I checked, linux-firmware-git is no longer required. With the usual linux firmware, an amf encode appears in obs.

**Comment by OzzyHelix** [comment]
thanks I will update it to reflect that

**Comment by OzzyHelix** [comment]
its updated to use linux-firmware now 
https://github.com/OzzyHelix/obs-studio-amf-tempfix/commit/97131cd13b71cae34231bc2f5f8aa154ba61bf92

**Comment by Weather-OS** [comment]
> its updated to use linux-firmware now
> [97131cd](https://github.com/OzzyHelix/obs-studio-amf-tempfix/commit/97131cd13b71cae34231bc2f5f8aa154ba61bf92)

I think you should probably remove the dependency because I’m almost certain that every arch install has linux-firmware already installed (or at least some variation of it).

**Comment by OzzyHelix** [comment]
its unclear to me if every version of linux-firmware works with this. I worry that removing the dependency will lead to future issues of it not working for some people who might not have it
