### ISSUE TITLE
Solved all dependencies. Still no AMF.

### ISSUE THREAD

**Issue by 3laws** [OzzyHelix/obs-studio-amf-tmpfix-for-arch#2]
I understand you are not the maintainer of the OG amf patch or anything but I'm curious if you ever got to a point where OBS launched with the proper VK icd and still no AMF was shown as an encoder option.

`obs-amf-test` gives:

`[1]    57329 segmentation fault (core dumped)  obs-amf-test`

**Comment by OzzyHelix** [comment]
`obs-amf-test` works for me you might be missing dependencies

**Comment by OzzyHelix** [comment]
@3law can you try building with this I am trying to see if I can fix it for you
https://github.com/OzzyHelix/obs-studio-amf-tempfix/tree/issue2

**Comment by OzzyHelix** [comment]
I believe there might be a problem with the dependencies in the build so I took the dependencies of `obs-studio-git` and combined them with the packages needed for amf

**Comment by 3laws** [comment]
Thanks for your reply. Still no success with the new dependencies. I think it's AMF itself, OBS runs absolutely just fine and logs look "fine" [but there's not a single AMF line](https://obsproject.com/logs/WOzWS2X9BQrAnksU). AFAIK AMF shouldn't conflict with other AMD pro related stuff like rocm or hip which I use for DaVinci and Blender respectively.

I tried using `amf-headers-git` and still nothing. I'm kinda lost on this now. What AMF packages do you have install? Sorry that you can't replicate my issue I'll try to replicate your set up as best as possible.

**Comment by OzzyHelix** [comment]
I have amf-amdgpu-pro, amf-headers and obs-streamfx-unstable installed but that last one I don't think should matter

**Comment by OzzyHelix** [comment]
I just checked the last one there doesn't matter

**Comment by OzzyHelix** [comment]
you have an AMD GPU right? because the amf stuff is for hardware encoding of h264 on AMD GPUs and requires AMD RX 5000 at the earliest

**Comment by OzzyHelix** [comment]
anything older than RDNA won't work for this

**Comment by 3laws** [comment]
> I just checked the last one there doesn't matter

Correct, deprecated for a long time for AMF now.

> you have an AMD GPU right? because the amf stuff is for hardware encoding of h264 on AMD GPUs and requires AMD RX 5000 at the earliest

![image](https://github.com/OzzyHelix/obs-studio-amf-tempfix/assets/4267075/149c2d1c-4790-42ba-8ac3-6b439679be92)

yup

ok so I'll guess it's the rest of the AMD stack that is causing the conflict, didn't see anything on the archwiki that raised any suspicion but I'll go through every single package and see what's left after the great purge. Appreciate your efforts, again. I'll report back eventually.

**Comment by OzzyHelix** [comment]
please make sure you have linux-firmware installed the git version isn't required for this to work anymore

**Comment by OzzyHelix** [comment]
I'm running into a new issue with this project updating the patches to a new version of OBS like 30.1.2 causes the patches to no longer apply due to code changes to OBS if anyone wants to submit pull requests updating the patches I will happily accept them but I am currently having to try and figure it out on my own

**Comment by OzzyHelix** [comment]
right now it is impossible to update the package to 30.1.2 for me there are too many changes between versions for the patch to work and I am not skilled enough to fix the patch I'm going to speak to my father tomorrow about it he is a ruby developer and I'm going to see if I can bring him on as a co-maintainer to fix the patch he likely won't get involved for much other than fixing the patch if he agrees to help me

**Comment by OzzyHelix** [comment]
help me tell the OBS devs that people want to use AMF in OBS with this I can't maintain this anymore read the readme and the link to the thing is here 
https://ideas.obsproject.com/posts/2591/please-enable-amf-amd-hw-encoding-options-on-linux

I also hope that obs-studio-amf will be updated but I am not sure it will
https://aur.archlinux.org/packages/obs-studio-amf

closing and archiving repo
